name: Prepare

on:
  push:
    branches: [main]
  pull_request:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04
    outputs:
      YARN_CACHE_DIR: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
      YARN_VERSION: ${{ steps.yarn-version.outputs.YARN_VERSION }}
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache directory
        run: echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"
        id: yarn-cache-dir
      - name: Get Yarn version
        run: echo "YARN_VERSION=$(yarn --version)" >> "$GITHUB_OUTPUT"
        id: yarn-version
      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
          key: yarn-cache-${{ runner.os }}-${{ steps.yarn-version.outputs.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}-${{ matrix.node-version }}
      - name: Install Yarn dependencies
        run: yarn --immutable
      - uses: ./.github/workflows/build-test.yml
        with:
          node-version: ${{ matrix.node-version }}
          yarn-version: ${{ steps.yarn-version.outputs.YARN_VERSION }}
          yarn-cache-dir: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}

